# Generated by Django 2.1.7 on 2019-03-07 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exams.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.CharField(blank=True, max_length=1000, null=True)),
                ('points', models.FloatField(blank=True, null=True, validators=[exams.models.validate_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaiable', models.BooleanField(default=False)),
                ('created_in', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('answered', models.BooleanField(default=False)),
                ('checking', models.BooleanField(default=False)),
                ('judged', models.BooleanField(default=False)),
                ('judged_in', models.DateTimeField(blank=True, null=True)),
                ('archivized', models.BooleanField(default=False)),
                ('archivized_in', models.DateTimeField(blank=True, null=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams_author', related_query_name='exam_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=500)),
                ('max_points', models.FloatField(validators=[exams.models.validate_positive])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', related_query_name='exam_question', to='exams.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_max_points', models.FloatField(blank=True, null=True)),
                ('scored_points', models.FloatField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Normal'), (2, 'Low'), (1, 'Failed')], null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', related_query_name='result', to='exams.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_students', related_query_name='result_studnet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assesment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assesments', related_query_name='exam_assesment', to='exams.Exam'),
        ),
        migrations.AddField(
            model_name='assesment',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_assesments', related_query_name='result_assesment', to='exams.Result'),
        ),
        migrations.AddField(
            model_name='assesment',
            name='student_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_assesments', related_query_name='answer_assesment', to='exams.Answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', related_query_name='exam_answer', to='exams.Exam'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_anwsers', related_query_name='question_anwser', to='exams.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers_author', related_query_name='answer_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
