# Generated by Django 2.1.7 on 2019-03-07 16:35

from django.db import migrations, models
import exams.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='commentary',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='points',
            field=models.FloatField(default=0, validators=[exams.models.validate_positive]),
            preserve_default=False,
        ),
    ]
